### ISSUE TITLE
Allow keywords to be passed in config.design-tokens.yml

### ISSUE THREAD

**Issue by cssgirl** [forumone/gesso#249]
For example 'transparent' in the case of a background color. Related convo:

> If I want to set a button to have a transparent background in the config.design-tokens.yml, what is the recommended way to make that happen? Using the keyword in single quotes/no quotes throws an error. Same for if I try to use a gradient (referenced from a color palette or directly passed).

**Comment by kmonahan** [comment]
@cssgirl,
Can you pull down https://github.com/forumone/gesso/compare/8.x-3.1-RC and see if that fixes the issue for you? I just pushed a change there so that any values in single or double-quoted strings in the `colors` section of `config.design-tokens.yml` will be used as-is. So you can do things like:
```
button:
  primary:
   background: 'transparent'
``` 
or
```
button:
  primary:
    text: 'inherit'
```

**Comment by dcmouyard** [comment]
@kmonahan The fix you made in 8.x-3.1-RC worked for me!

**Comment by dcmouyard** [comment]
This fix is in 8.x-3.x.
