### ISSUE TITLE
Remove linting rule on disallowing qualifying a selector by type

### ISSUE THREAD

**Issue by dcmouyard** [forumone/gesso#294]
I’ve heard grumblings that people have to frequently override the [selector-no-qualifying-type](https://stylelint.io/user-guide/rules/selector-no-qualifying-type) Stylelint rule.

I’m leaning towards keeping this rule since this type of code can contribute to specificity wars. If you really need this you can add a comment to override it, which I think provides enough friction to force one to think whether they _really_ need to do this.

Any thoughts?

**Comment by kmonahan** [comment]
Yeah, I'm with you on this one. Having the rule in place means that you need to think hard about whether you really need that level of specificity and if you do, add a comment to disable it (preferably with an explanation of why). I do think the ignore: attribute should be part of the rule though (haven't looked to see if that is what we have already or not), since it's reasonable to need to set up some generic form field styling with things like `input[type="text"]` and or to tie styling to some other attribute, i.e. visually hiding something when `[aria-hidden="true"]`.

**Comment by coreylafferty** [comment]
I was the (or at least one) of the grumblers, but this is a rare case so I think adding an ignore comment will be fine.  Closing.
