### ISSUE TITLE
Vertical spacing

### ISSUE THREAD

**Issue by dcmouyard** [forumone/gesso#306]
Currently in Gesso, we remove the top margins on most things and only set a bottom margin, usually based on one of the spacing design tokens.
```
p {
  margin: 0 0 rem(gesso-spacing(sm));
}
```

One notable exception to this is used for headings, where we add top margin if there’s a sibling just before the heading.
```
%hN {
  margin: 0 0 rem(gesso-spacing(sm));

  // Add top margin when headers are preceded by other elements (p, ul, etc.)
  * + & {
    margin-top: 1em;
  }
}
```

This approach means that most things have a bottom margin, and in certain cases we want to remove the bottom margin on the last item in something.
```
.message__content {
  > *:last-child {
    margin-bottom: 0;
  }
}
```

The USWDS uses an approach where items don’t get top or bottom margins by default, but get added only if items are before or after it, similar to how we’re currently handling headings.
```
p {
  margin: 0;

  // Add top margin when preceded by another element.
  * + & {
    margin-top: 1em;
  }

  // Add top margin to item directly after this.
  + * {
    margin-top: 1em;
  }
}
```

How do folks feel about switching to the USWDS approach?

**Comment by ghost** [comment]
I like this idea - I ran into a small issue the other day because there wasn't another element after my component, and had to modify the margins manually, so this makes sense to me.

**Comment by coreylafferty** [comment]
I can't think of any reason this would be a problem, so let's do it.  Seems a little simpler than always having to add last-child rules.

**Comment by dcmouyard** [comment]
I’m starting to regret adding this to Gesso, since I often _want_ the last item in something to have a bottom margin, and usually more often than I _don’t_ want the last item to have a bottom margin.

Anyone else feel this way?

**Comment by coreylafferty** [comment]
@dcmouyard In most cases, it's worked well for me.  Most of the time I don't want margin on the last item.  

However, I've run into a different problem.. Because I'm using this mixin on lots of things, I'm often hitting conflicting rules and having to use the $important: true override.  That's worked so far but I know eventually I'm going to hit a conflict between two rules that are both already set to important and I don't know how I'm going to resolve that.  

Since we're both having issues, I wouldn't be opposed to reverting this or finding a different solution.

**Comment by dcmouyard** [comment]
We removed this new vertical spacing approach from Gesso
