### ISSUE TITLE
Caching with gulp vs gulp build

### ISSUE THREAD

**Issue by ghost** [forumone/gesso#366]
Hi there! I'm having a strange issue where it seems that if I run `gulp` I'm not seeing changes in Pattern Lab - either twig, yml, or SASS changes. Whereas if I run `gulp build` the changes show up immediately after the build. Is there a difference in the way `gulp build` behaves to rebuild cache or something? Thanks!

**Comment by coreylafferty** [comment]
@dutton242 I don't believe there's really any difference between the default `gulp` task and `gulp build`, other than some minor changes to how the JS files are bundled.  Otherwise they're identical, so I don't see how that could affect caching.  When you run the default task are you seeing it start watching for changes (i.e., it should say 'Starting WatchFiles').  After that, if you make any changes to Sass, Twig, etc. you should see it recompile the necessary files -- once it finishes doing so, you should see the changes in your browser on refresh.  

If that all seems to be working I'd check your browser cache settings (for example, if using Chrome I'd check under the settings / network settings in the inspector itself to make sure the cache is completely disabled when the inspector is open).

**Comment by ghost** [comment]
@coreylafferty, thank you for the explanation. I've had these issues for a while and originally in some other issue queues folks figured out that it's most likely Docker that is the issue. By restarting Docker, those assets will update - sometimes! I sort of thought it could be semi-related to this `gulp` vs `gulp build` thing. Glad to know it' not doing anything totally different. Have a good one!
