### ISSUE TITLE
"required" Vs. "is-reqiured" in fieldset.html.twig

### ISSUE THREAD

**Issue by johnbburg** [forumone/gesso#391]
This template adds a "is-required" value for required fields. However, Drupal's webform module uses some javascript to search for a "required" class to add a the required attribute to radio buttons.

I'mnot sure what is using 'is-required" but I suggest we add a "required" class in this case as well. 

```
{% set addClasses = [
  'fieldset',
  required ? 'is-required',
  required ? 'required',
  'js-form-wrapper',
] %}
```` 

See 
https://www.drupal.org/project/webform/issues/2996916
https://www.drupal.org/project/webform/issues/2945890
https://www.drupal.org/project/webform/issues/2856795

**Comment by johnbburg** [comment]
I can't really tell what uses the "is-required" class. 

Also, I just saw that we are explicitly removing the "required" class right above. What's the motivation for this?

https://github.com/forumone/gesso/blob/00a9d99a8e51fa13fe039b59027ca26c2ff4981f/templates/form/fieldset.html.twig#L2

**Comment by dcmouyard** [comment]
We use the `is-` and `has-` naming convention for states of a component, which is why we use `is-required` instead of `required`. 

JavaScript should really target `js-` prefixed classes or data attributes, but not all modules follow that standard.

We can easily add the required class back in, though, to fix this issue.
