### ISSUE TITLE
SlideToggle doesn't appear to work correctly

### ISSUE THREAD

**Issue by coreylafferty** [forumone/gesso#474]
Haven't confirmed this myself, but heard from another developer that while the SlideUp and SlideDown functions work fine from our `_slide.es6.js` file, SlideToggle is broken.

**Comment by kmonahan** [comment]
I'm not able to replicate this one. Since there wasn't previously a way to demo/test slideToggle in Pattern Lab, I opened https://github.com/forumone/gesso/pull/479. Tried the demo in Firefox and Chrome, but had no issues with slideToggle. If this was an issue that was reported on a project, it might be that some other project CSS or JS is interacting with the slideToggle, but I'd need to see it in context to troubleshoot.
