### ISSUE TITLE
Create call to action Storybook component and Drupal paragraph template

### ISSUE THREAD

**Issue by carsoncho** [forumone/gesso#838]
A common component we have on all of our sites is a Call to Action component. The thought here would be that component would have at least the following fields:

- Heading
- Body text/copy
- Link
- (Optional) image?

I'm unsure if we need to provide designs or anything for that, but we feel this would be a useful component to include as part of our starter projects and thus part of Gesso.

**Comment by coreylafferty** [comment]
@carsoncho We discussed this during the Gesso development meeting and the general consensus was that callouts vary wildly in design and are typically fairly easy to develop, so a starting one may not be that useful as it'd often be easier to start from scratch rather than undo and modify an existing one.  

That said, if designers ARE moving towards a more standardized approach to callouts or if their starting design templates have one (which might lead designers to stick somewhat closely to its design and layout), then it might be valuable to have an out of the box option.  

If one of those things is true and you can provide a design then we could discuss further. Thanks!

**Comment by coreylafferty** [comment]
@carsoncho We didn't realize this was part of the Drupal starter paragraphs project when we discussed this earlier. In that case this makes more sense coming from that direction... we'd just need to give it very minimal design on the theming side, but I can do that as well as create the supporting templates once the fields are created on the backend. If you can point me to a PR or something for the backend portion, I can add supporting templates and styles to Gesso and help with a default template in the module if needed.

**Comment by coreylafferty** [comment]
@carsoncho Did this paragraph type ever get created as part of drupal starter?

**Comment by carsoncho** [comment]
@coreylafferty Yes, this component now exists as part of drupal-starter. This is included in the latest drupal-starter now ([https://github.com/forumone/drupal-project/tree/main/web/modules/starterkit/f1_call_to_action_paragraph](https://github.com/forumone/drupal-project/tree/main/web/modules/starterkit/f1_call_to_action_paragraph)). This follows the rough content model proposed above.

**Comment by coreylafferty** [comment]
Next step -- create a Storybook "call to action" component with a very simple design and a Drupal paragraph template that matches the configuration (field machine names, etc.) in the Drupal Project (https://github.com/forumone/drupal-project/tree/main/web/modules/starterkit/f1_call_to_action_paragraph).  This is similar to what we've done for the Hero and Accordion paragraphs.

**Comment by carsoncho** [comment]
Apologies, I didn't keep up with this issue's progress! Happy to see this is now implemented now. We can call this issue closed.
